name: Code-quality
on:
    push:
        branches: [ main ]
jobs:
    code-quality:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '17' 
                  
            - name: Cache mven Dependencies
              uses: actions/cache@v3
              with:
                path: ~/.m2
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            - name: Run Checkstyle
              run: mvn checkstyle:checkstyle