name: Tests 
on:
    push:
        branches: [ docker ]
    workflow_run:
        workflows: ["Code-quality"]
        types:
            - completed
jobs:
    tests:
        if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '17' 
            
            - name: Building with Maven
              run: mvn clean install -DskipTests

            - name: Run Tests
              run: mvn test